### ISSUE TITLE
lgeos import fail (regression in 2.0)

### ISSUE THREAD

**Issue by Nodjo** [shapely/shapely#1661]
I'm using shapely in docker. When compiling against 1.8.5post1 this works well:

`from shapely.geos import lgeos`

However, against shapely 2.0 I'm getting the following error:

```
     from shapely.geos import lgeos
 ImportError: cannot import name 'lgeos' from 'shapely.geos' (/usr/local/lib/python3.8/dist-packages/shapely/geos.py)
```

Forcing version below 2.0 (it picks up 1.8.5post1) fixes the issue

**Comment by tomplex** [comment]
Shapely 2.0 deprecated direct usage of the GEOS library in favor of a custom built, vectorized C / Cython wrapper of GEOS which you can see in the source code [here](https://github.com/shapely/shapely/tree/main/src). To continue using this behavior, you'll have to pin to a version before 2.0. But probably it's best if you update your codebase to not use the lgeos handle directly.

**Comment by Nodjo** [comment]
OK, thank you !

**Comment by jorisvandenbossche** [comment]
To add to what @tomplex already said: normally you should not need to use `lgeos`, or at least what you did with `lgeos` before will typically be supported by other modules in shapely, when updating your code to work with shapely 2.0.

But feel free to give some more details about how you used `lgeos` before, or if you run into any problem replacing that code.

**Comment by Nodjo** [comment]
I'm currently using to try to fix invalid polygons which sometimes occur

`lgeos.GEOSMakeValid(geom)
`

**Comment by jorisvandenbossche** [comment]
That function is available in `shapely.validation.make_valid` (and also `shapely.make_valid` starting from 2.0)

**Comment by Nodjo** [comment]
Perfect, thank you !

**Comment by idanmiara** [comment]
> Perfect, thank you !

Please close the issue if it is resolved. Thanks!
